name: Sync Upstream

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/pbs05/uboot-an758x.git
          git fetch upstream main

      - name: Sync main
        run: |
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
